modLoader="javafml"
loaderVersion="[2,)"
license="All rights reserved"

[[mods]]
modId="gh_hud_visuals"
version="0.0.1"
displayName="HUD & Visuals Subpack"
description='''
HUD and Visuals Subpack for Grey Horizons RPG.
    '''

[[mixins]]
config="hud_visuals.mixins.json"

[[dependencies.gh_hud_visuals]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.gh_hud_visuals]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"